ava-stats:
  - ATTACK_DAMAGE
  - ATTACK_SPEED
  - CRITICAL_STRIKE_CHANCE
  - CRITICAL_STRIKE_POWER
  - SKILL_CRITICAL_STRIKE_CHANCE
  - SKILL_CRITICAL_STRIKE_POWER
  - BLOCK_POWER
  - BLOCK_RATING
  - BLOCK_COOLDOWN_REDUCTION
  - DODGE_RATING
  - DODGE_COOLDOWN_REDUCTION
  - PARRY_RATING
  - PARRY_COOLDOWN_REDUCTION
  - COOLDOWN_REDUCTION
  - RANGE
  - MANA_COST
  - STAMINA_COST
  - ARROW_VELOCITY
  - PVE_DAMAGE
  - PVP_DAMAGE
  - BLUNT_POWER
  - BLUNT_RATING
  - WEAPON_DAMAGE
  - SKILL_DAMAGE
  - PROJECTILE_DAMAGE
  - MAGIC_DAMAGE
  - PHYSICAL_DAMAGE
  - DEFENSE
  - DAMAGE_REDUCTION
  - FALL_DAMAGE_REDUCTION
  - PROJECTILE_DAMAGE_REDUCTION
  - PHYSICAL_DAMAGE_REDUCTION
  - FIRE_DAMAGE_REDUCTION
  - MAGIC_DAMAGE_REDUCTION
  - PVE_DAMAGE_REDUCTION
  - PVP_DAMAGE_REDUCTION
  - UNDEAD_DAMAGE
  - LIFESTEAL
  - SPELL_VAMPIRISM
  - ARMOR_TOUGHNESS
  - ARMOR
  - MAX_HEALTH
  - MAX_MANA
  - ITEM_COOLDOWN
  - NOTE_WEIGHT
  - KNOCKBACK
  - RECOIL
  - DEATH_DOWNGRADE_CHANCE
#根据玩家等级生成怪物的等级世界
radius: 50.0
random: true
max-cal: 5
power: ATTACK_DAMAGE*2
white-list: true
world:
  - world